"use client";

import { useState } from "react";
import { Shield, Clock, Check, X, Calendar, Search } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export default function WardenVisitorsPage() {
  const [visitors, setVisitors] = useState([
    { id: "V-1", guestName: "Sanjay Mehta", relation: "Father (Aarav Mehta)", room: "204-B", checkIn: "10:30 AM", checkOut: "04:15 PM", date: "Today", status: "checked-out" },
    { id: "V-2", guestName: "Nirmala Das", relation: "Mother (Rohan Das)", room: "201-A", checkIn: "02:15 PM", checkOut: "--", date: "Today", status: "checked-in" },
    { id: "V-3", guestName: "Rajesh Roy", relation: "Local Guardian (Aditya Roy)", room: "105-B", checkIn: "03:30 PM", checkOut: "--", date: "Today", status: "checked-in" },
    { id: "V-4", guestName: "Mahendra Mishra", relation: "Father (Sumit Mishra)", room: "302-C", checkIn: "09:00 AM", checkOut: "02:30 PM", date: "Yesterday", status: "checked-out" }
  ]);

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-extrabold font-[family-name:var(--font-heading)]">Visitor & Security Logs</h1>
          <p className="text-muted-foreground mt-1">Track family members, parent check-ins, local guardians, and security check out stamps.</p>
        </div>
      </div>

      <div className="grid md:grid-cols-12 gap-6">
        <div className="md:col-span-8 space-y-4">
          <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Today&apos;s Visitor Roster</h3>
          {visitors.map((v, idx) => (
            <Card key={idx} className="border-border/50">
              <CardContent className="p-4 flex items-center justify-between text-sm">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-500 shrink-0">
                    <Shield className="w-4.5 h-4.5" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold">{v.guestName}</span>
                      <Badge variant="outline" className="text-[9px]">{v.relation}</Badge>
                    </div>
                    <p className="text-xs text-muted-foreground">Visiting Room: {v.room} • Check In: {v.checkIn} • Check Out: {v.checkOut}</p>
                  </div>
                </div>

                <Badge className={v.status === "checked-in" ? "bg-green-500/10 text-green-500 border border-green-500/20" : "bg-secondary text-muted-foreground"}>
                  {v.status}
                </Badge>
              </CardContent>
            </Card>
          ))}
        </div>

        <Card className="md:col-span-4 border-border/50 p-6 space-y-4 h-fit">
          <h3 className="text-lg font-bold font-[family-name:var(--font-heading)]">Gate Regulations</h3>
          <p className="text-xs text-muted-foreground leading-relaxed">
            All guests must produce an OTP generated by the student or obtain direct phone approval from the warden before entering the hostel blocks.
          </p>
          <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/10 text-xs">
            <span className="font-bold text-emerald-500 block mb-0.5">Visitor Hours:</span>
            Daily 09:00 AM to 06:30 PM. No overnight guest stays permitted without committee waiver.
          </div>
        </Card>
      </div>
    </div>
  );
}
